// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LoadController(	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
  output        io_cmd_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [6:0]  io_cmd_bits_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [4:0]  io_cmd_bits_cmd_inst_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [4:0]  io_cmd_bits_cmd_inst_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_inst_xd,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_inst_xs1,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_inst_xs2,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [4:0]  io_cmd_bits_cmd_inst_rd,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [6:0]  io_cmd_bits_cmd_inst_opcode,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [63:0] io_cmd_bits_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [63:0] io_cmd_bits_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_cease,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_wfi,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [31:0] io_cmd_bits_cmd_status_isa,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_dprv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_dv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_prv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_v,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_sd,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [22:0] io_cmd_bits_cmd_status_zero2,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mpv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_gva,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mbe,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_sbe,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_sxl,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_uxl,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_sd_rv32,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [7:0]  io_cmd_bits_cmd_status_zero1,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_tsr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_tw,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_tvm,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_sum,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mprv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_xs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_fs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_mpp,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [1:0]  io_cmd_bits_cmd_status_vs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_spp,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mpie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_ube,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_spie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_upie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_mie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_hie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_sie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_cmd_status_uie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [5:0]  io_cmd_bits_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_from_matmul_fsm,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_cmd_bits_from_conv_fsm,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_dma_req_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [39:0] io_dma_req_bits_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_laddr_is_acc_addr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_laddr_accumulate,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_laddr_read_full_acc_row,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [2:0]  io_dma_req_bits_laddr_norm_cmd,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [10:0] io_dma_req_bits_laddr_garbage,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_laddr_garbage_bit,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [13:0] io_dma_req_bits_laddr_data,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [15:0] io_dma_req_bits_cols,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [15:0] io_dma_req_bits_repeats,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [31:0] io_dma_req_bits_scale,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_has_acc_bitwidth,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_all_zeros,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [15:0] io_dma_req_bits_block_stride,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [7:0]  io_dma_req_bits_pixel_repeats,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [7:0]  io_dma_req_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_debug,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_cease,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_wfi,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [31:0] io_dma_req_bits_status_isa,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_dprv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_dv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_prv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_v,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_sd,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [22:0] io_dma_req_bits_status_zero2,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mpv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_gva,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mbe,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_sbe,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_sxl,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_uxl,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_sd_rv32,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [7:0]  io_dma_req_bits_status_zero1,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_tsr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_tw,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_tvm,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mxr,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_sum,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mprv,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_xs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_fs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_mpp,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [1:0]  io_dma_req_bits_status_vs,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_spp,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mpie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_ube,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_spie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_upie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_mie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_hie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_sie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_dma_req_bits_status_uie,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_dma_resp_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [15:0] io_dma_resp_bits_bytesRead,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input  [7:0]  io_dma_resp_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  input         io_completed_ready,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_completed_valid,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output [5:0]  io_completed_bits,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_busy,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_counter_event_signal_8,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_counter_event_signal_9,	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
  output        io_counter_event_signal_10	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:18:14]
);

  wire             _cmd_tracker_io_alloc_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27]
  wire             _cmd_tracker_io_alloc_bits_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27]
  wire             _cmd_tracker_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27]
  wire             _cmd_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [6:0]       _cmd_q_io_deq_bits_cmd_inst_funct;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [63:0]      _cmd_q_io_deq_bits_cmd_rs1;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [63:0]      _cmd_q_io_deq_bits_cmd_rs2;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [5:0]       _cmd_q_io_deq_bits_rob_id_bits;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg  [1:0]       control_state;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30]
  reg  [39:0]      strides_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20]
  reg  [39:0]      strides_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20]
  reg  [39:0]      strides_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20]
  reg  [31:0]      scales_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19]
  reg  [31:0]      scales_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19]
  reg  [31:0]      scales_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19]
  reg              shrinks_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20]
  reg              shrinks_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20]
  reg              shrinks_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20]
  reg  [13:0]      block_strides_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26]
  reg  [13:0]      block_strides_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26]
  reg  [13:0]      block_strides_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26]
  reg  [4:0]       pixel_repeats_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26]
  reg  [4:0]       pixel_repeats_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26]
  reg  [4:0]       pixel_repeats_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26]
  reg  [3:0]       row_counter;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:40:28]
  wire [1:0]       state_id = (|_cmd_q_io_deq_bits_cmd_inst_funct) ? (_cmd_q_io_deq_bits_cmd_inst_funct == 7'h1 ? 2'h1 : {_cmd_q_io_deq_bits_cmd_inst_funct == 7'hE, 1'h0}) : _cmd_q_io_deq_bits_cmd_rs1[4:3];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:52:50, :61:65, :62:30, :64:{21,46}, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [3:0][39:0] _GEN = {{strides_0}, {strides_2}, {strides_1}, {strides_0}};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :76:37]
  wire             _io_dma_req_bits_repeats_T = _GEN[state_id] == 40'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:64:21, :76:37]
  wire [4:0]       actual_rows_read = _io_dma_req_bits_repeats_T & (|_cmd_q_io_deq_bits_cmd_rs1) ? 5'h1 : _cmd_q_io_deq_bits_cmd_rs2[52:48];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:45:43, :72:25, :76:{29,37,45}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire             _cmd_tracker_io_alloc_valid_T = control_state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30, :99:38]
  wire             io_counter_event_signal_8_0 = control_state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30, :100:19]
  wire             io_counter_event_signal_9_0 = control_state == 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30, :101:20]
  wire             io_dma_req_valid_0 = _cmd_tracker_io_alloc_valid_T & _cmd_q_io_deq_valid & (|_cmd_q_io_deq_bits_cmd_inst_funct) & _cmd_tracker_io_alloc_ready | io_counter_event_signal_8_0 | io_counter_event_signal_9_0 & (|row_counter);	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:40:28, :64:46, :94:27, :99:{38,62,75,85,116}, :100:{19,49}, :101:{20,37,52}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0][13:0] _GEN_0 = {{block_strides_0}, {block_strides_2}, {block_strides_1}, {block_strides_0}};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26, :106:32]
  wire [3:0][31:0] _GEN_1 = {{scales_0}, {scales_2}, {scales_1}, {scales_0}};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19, :107:25]
  wire [3:0]       _GEN_2 = {{shrinks_0}, {shrinks_2}, {shrinks_1}, {shrinks_0}};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20, :108:81]
  wire             io_dma_req_bits_has_acc_bitwidth_0 = _cmd_q_io_deq_bits_cmd_rs2[31] & ~_GEN_2[state_id];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:45:43, :64:21, :108:{78,81}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0][4:0]  _GEN_3 = {{pixel_repeats_0}, {pixel_repeats_2}, {pixel_repeats_1}, {pixel_repeats_0}};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26, :111:33]
  wire             cmd_tracker_io_alloc_valid = _cmd_tracker_io_alloc_valid_T & _cmd_q_io_deq_valid & (|_cmd_q_io_deq_bits_cmd_inst_funct);	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:64:46, :99:38, :114:{71,84}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [10:0]      _cmd_tracker_io_alloc_bits_bytes_to_read_T_2 = {4'h0, _cmd_q_io_deq_bits_cmd_rs2[38:32]} * {6'h0, actual_rows_read};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, :76:29, :116:48, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [10:0]      _cmd_tracker_io_alloc_bits_bytes_to_read_T_4 = io_dma_req_bits_has_acc_bitwidth_0 ? {_cmd_tracker_io_alloc_bits_bytes_to_read_T_2[8:0], 2'h0} : _cmd_tracker_io_alloc_bits_bytes_to_read_T_2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:108:78, :116:{8,48,67}]
  wire             _cmd_id_T = cmd_tracker_io_alloc_valid & _cmd_tracker_io_alloc_ready;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40, generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27, :114:{71,84}]
  reg              cmd_id_buf;	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
  wire             _last_row_T_4 = io_dma_req_ready & io_dma_req_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:99:116, :100:49, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [4:0]       _GEN_4 = {1'h0, row_counter};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:40:28, generators/gemmini/src/main/scala/gemmini/Util.scala:27:15]
  wire             last_row = row_counter == 4'h0 | _GEN_4 == actual_rows_read - 5'h1 & _last_row_T_4;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :40:28, :76:29, :165:{34,42,58,78,83}, generators/gemmini/src/main/scala/gemmini/Util.scala:27:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:19:11]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/Util.scala:19:11]
      if (_last_row_T_4 & ~reset & _GEN_0[state_id] < {9'h0, _cmd_q_io_deq_bits_cmd_rs2[52:48]}) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:45:43, :64:21, :106:32, :136:{11,25}, src/main/scala/chisel3/util/Decoupled.scala:51:35, :362:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:136:11]
          $error("Assertion failed\n    at LoadController.scala:136 assert(block_stride >= rows)\n");	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:136:11]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:136:11]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:136:11]
      end
      if (~reset & _cmd_id_T & _cmd_tracker_io_alloc_bits_bytes_to_read_T_4 == 11'h0) begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40, generators/gemmini/src/main/scala/gemmini/LoadController.scala:116:8, :136:11, :189:{9,40,83}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:189:9]
          $error("Assertion failed: A single mvin instruction must load more than 0 bytes\n    at LoadController.scala:189 assert(!(cmd_tracker.io.alloc.fire() && cmd_tracker.io.alloc.bits.bytes_to_read === 0.U), \"A single mvin instruction must load more than 0 bytes\")\n");	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:189:9]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:189:9]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:189:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [4:0]       _row_counter_max_T = actual_rows_read - 5'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:76:29, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28]
  wire [4:0]       _pixel_repeats_T_1 = _cmd_q_io_deq_bits_cmd_rs1[12:8] == 5'h0 ? 5'h1 : _cmd_q_io_deq_bits_cmd_rs1[12:8];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:52:50, :148:{30,52}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      control_state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30]
      row_counter <= 4'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :40:28]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      if (_cmd_tracker_io_alloc_valid_T) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:99:38]
        if (_cmd_id_T)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40]
          control_state <= _last_row_T_4 ? 2'h2 : 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30, :153:31, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      end
      else if (io_counter_event_signal_8_0) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:100:19]
        if (_last_row_T_4)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
          control_state <= 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30]
      end
      else if (io_counter_event_signal_9_0 & last_row)	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30, :101:20, :140:26, :165:42, :167:23, :168:23]
        control_state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:31:30]
      if (_last_row_T_4)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        row_counter <= _row_counter_max_T == 5'h0 ? 4'h0 : _GEN_4 >= actual_rows_read - 5'h1 ? 4'h1 - (_row_counter_max_T[3:0] - row_counter) - 4'h1 : row_counter + 4'h1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :40:28, :76:29, generators/gemmini/src/main/scala/gemmini/Util.scala:18:28, :19:28, :27:15, :30:{10,17,21,47,54,59}, src/main/scala/chisel3/util/Mux.scala:126:16]
    end
    if (_cmd_tracker_io_alloc_valid_T & _cmd_q_io_deq_valid & ~(|_cmd_q_io_deq_bits_cmd_inst_funct) & state_id == 2'h0) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :64:{21,46}, :99:38, :140:26, :142:24, :143:24, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      strides_0 <= _cmd_q_io_deq_bits_cmd_rs2[39:0];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      scales_0 <= _cmd_q_io_deq_bits_cmd_rs1[63:32];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      shrinks_0 <= _cmd_q_io_deq_bits_cmd_rs1[2];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      block_strides_0 <= _cmd_q_io_deq_bits_cmd_rs1[29:16];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      pixel_repeats_0 <= _pixel_repeats_T_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26, :148:30]
    end
    if (_cmd_tracker_io_alloc_valid_T & _cmd_q_io_deq_valid & ~(|_cmd_q_io_deq_bits_cmd_inst_funct) & state_id == 2'h1) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :64:{21,46}, :99:38, :140:26, :142:24, :143:24, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      strides_1 <= _cmd_q_io_deq_bits_cmd_rs2[39:0];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      scales_1 <= _cmd_q_io_deq_bits_cmd_rs1[63:32];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      shrinks_1 <= _cmd_q_io_deq_bits_cmd_rs1[2];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      block_strides_1 <= _cmd_q_io_deq_bits_cmd_rs1[29:16];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      pixel_repeats_1 <= _pixel_repeats_T_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26, :148:30]
    end
    if (_cmd_tracker_io_alloc_valid_T & _cmd_q_io_deq_valid & ~(|_cmd_q_io_deq_bits_cmd_inst_funct) & state_id == 2'h2) begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :64:{21,46}, :99:38, :140:26, :142:24, :143:24, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      strides_2 <= _cmd_q_io_deq_bits_cmd_rs2[39:0];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:33:20, :144:18, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      scales_2 <= _cmd_q_io_deq_bits_cmd_rs1[63:32];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:34:19, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      shrinks_2 <= _cmd_q_io_deq_bits_cmd_rs1[2];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:35:20, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      block_strides_2 <= _cmd_q_io_deq_bits_cmd_rs1[29:16];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:36:26, :52:50, src/main/scala/chisel3/util/Decoupled.scala:362:21]
      pixel_repeats_2 <= _pixel_repeats_T_1;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:37:26, :148:30]
    end
    if (_cmd_id_T)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40]
      cmd_id_buf <= _cmd_tracker_io_alloc_bits_cmd_id;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
        control_state = _RANDOM[4'h0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :31:30]
        strides_0 = {_RANDOM[4'h0][31:2], _RANDOM[4'h1][9:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :31:30, :33:20]
        strides_1 = {_RANDOM[4'h1][31:10], _RANDOM[4'h2][17:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :33:20]
        strides_2 = {_RANDOM[4'h2][31:18], _RANDOM[4'h3][25:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :33:20]
        scales_0 = {_RANDOM[4'h3][31:26], _RANDOM[4'h4][25:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :33:20, :34:19]
        scales_1 = {_RANDOM[4'h4][31:26], _RANDOM[4'h5][25:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19]
        scales_2 = {_RANDOM[4'h5][31:26], _RANDOM[4'h6][25:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19]
        shrinks_0 = _RANDOM[4'h6][26];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19, :35:20]
        shrinks_1 = _RANDOM[4'h6][27];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19, :35:20]
        shrinks_2 = _RANDOM[4'h6][28];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19, :35:20]
        block_strides_0 = {_RANDOM[4'h6][31:29], _RANDOM[4'h7][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :34:19, :36:26]
        block_strides_1 = _RANDOM[4'h7][24:11];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26]
        block_strides_2 = {_RANDOM[4'h7][31:25], _RANDOM[4'h8][6:0]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26]
        pixel_repeats_0 = _RANDOM[4'h8][11:7];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26, :37:26]
        pixel_repeats_1 = _RANDOM[4'h8][16:12];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26, :37:26]
        pixel_repeats_2 = _RANDOM[4'h8][21:17];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26, :37:26]
        row_counter = _RANDOM[4'h8][25:22];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26, :40:28]
        cmd_id_buf = _RANDOM[4'h8][26];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :36:26, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue8_GemminiCmd cmd_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                          (clock),
    .reset                          (reset),
    .io_enq_ready                   (io_cmd_ready),
    .io_enq_valid                   (io_cmd_valid),
    .io_enq_bits_cmd_inst_funct     (io_cmd_bits_cmd_inst_funct),
    .io_enq_bits_cmd_inst_rs2       (io_cmd_bits_cmd_inst_rs2),
    .io_enq_bits_cmd_inst_rs1       (io_cmd_bits_cmd_inst_rs1),
    .io_enq_bits_cmd_inst_xd        (io_cmd_bits_cmd_inst_xd),
    .io_enq_bits_cmd_inst_xs1       (io_cmd_bits_cmd_inst_xs1),
    .io_enq_bits_cmd_inst_xs2       (io_cmd_bits_cmd_inst_xs2),
    .io_enq_bits_cmd_inst_rd        (io_cmd_bits_cmd_inst_rd),
    .io_enq_bits_cmd_inst_opcode    (io_cmd_bits_cmd_inst_opcode),
    .io_enq_bits_cmd_rs1            (io_cmd_bits_cmd_rs1),
    .io_enq_bits_cmd_rs2            (io_cmd_bits_cmd_rs2),
    .io_enq_bits_cmd_status_debug   (io_cmd_bits_cmd_status_debug),
    .io_enq_bits_cmd_status_cease   (io_cmd_bits_cmd_status_cease),
    .io_enq_bits_cmd_status_wfi     (io_cmd_bits_cmd_status_wfi),
    .io_enq_bits_cmd_status_isa     (io_cmd_bits_cmd_status_isa),
    .io_enq_bits_cmd_status_dprv    (io_cmd_bits_cmd_status_dprv),
    .io_enq_bits_cmd_status_dv      (io_cmd_bits_cmd_status_dv),
    .io_enq_bits_cmd_status_prv     (io_cmd_bits_cmd_status_prv),
    .io_enq_bits_cmd_status_v       (io_cmd_bits_cmd_status_v),
    .io_enq_bits_cmd_status_sd      (io_cmd_bits_cmd_status_sd),
    .io_enq_bits_cmd_status_zero2   (io_cmd_bits_cmd_status_zero2),
    .io_enq_bits_cmd_status_mpv     (io_cmd_bits_cmd_status_mpv),
    .io_enq_bits_cmd_status_gva     (io_cmd_bits_cmd_status_gva),
    .io_enq_bits_cmd_status_mbe     (io_cmd_bits_cmd_status_mbe),
    .io_enq_bits_cmd_status_sbe     (io_cmd_bits_cmd_status_sbe),
    .io_enq_bits_cmd_status_sxl     (io_cmd_bits_cmd_status_sxl),
    .io_enq_bits_cmd_status_uxl     (io_cmd_bits_cmd_status_uxl),
    .io_enq_bits_cmd_status_sd_rv32 (io_cmd_bits_cmd_status_sd_rv32),
    .io_enq_bits_cmd_status_zero1   (io_cmd_bits_cmd_status_zero1),
    .io_enq_bits_cmd_status_tsr     (io_cmd_bits_cmd_status_tsr),
    .io_enq_bits_cmd_status_tw      (io_cmd_bits_cmd_status_tw),
    .io_enq_bits_cmd_status_tvm     (io_cmd_bits_cmd_status_tvm),
    .io_enq_bits_cmd_status_mxr     (io_cmd_bits_cmd_status_mxr),
    .io_enq_bits_cmd_status_sum     (io_cmd_bits_cmd_status_sum),
    .io_enq_bits_cmd_status_mprv    (io_cmd_bits_cmd_status_mprv),
    .io_enq_bits_cmd_status_xs      (io_cmd_bits_cmd_status_xs),
    .io_enq_bits_cmd_status_fs      (io_cmd_bits_cmd_status_fs),
    .io_enq_bits_cmd_status_mpp     (io_cmd_bits_cmd_status_mpp),
    .io_enq_bits_cmd_status_vs      (io_cmd_bits_cmd_status_vs),
    .io_enq_bits_cmd_status_spp     (io_cmd_bits_cmd_status_spp),
    .io_enq_bits_cmd_status_mpie    (io_cmd_bits_cmd_status_mpie),
    .io_enq_bits_cmd_status_ube     (io_cmd_bits_cmd_status_ube),
    .io_enq_bits_cmd_status_spie    (io_cmd_bits_cmd_status_spie),
    .io_enq_bits_cmd_status_upie    (io_cmd_bits_cmd_status_upie),
    .io_enq_bits_cmd_status_mie     (io_cmd_bits_cmd_status_mie),
    .io_enq_bits_cmd_status_hie     (io_cmd_bits_cmd_status_hie),
    .io_enq_bits_cmd_status_sie     (io_cmd_bits_cmd_status_sie),
    .io_enq_bits_cmd_status_uie     (io_cmd_bits_cmd_status_uie),
    .io_enq_bits_rob_id_bits        (io_cmd_bits_rob_id_bits),
    .io_enq_bits_from_matmul_fsm    (io_cmd_bits_from_matmul_fsm),
    .io_enq_bits_from_conv_fsm      (io_cmd_bits_from_conv_fsm),
    .io_deq_ready                   (_cmd_tracker_io_alloc_valid_T ? _cmd_q_io_deq_valid & ~(|_cmd_q_io_deq_bits_cmd_inst_funct) : ~io_counter_event_signal_8_0 & io_counter_event_signal_9_0 & last_row),	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:64:46, :81:13, :99:38, :100:19, :101:20, :140:26, :142:24, :143:24, :165:42, :167:23, src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_deq_valid                   (_cmd_q_io_deq_valid),
    .io_deq_bits_cmd_inst_funct     (_cmd_q_io_deq_bits_cmd_inst_funct),
    .io_deq_bits_cmd_rs1            (_cmd_q_io_deq_bits_cmd_rs1),
    .io_deq_bits_cmd_rs2            (_cmd_q_io_deq_bits_cmd_rs2),
    .io_deq_bits_cmd_status_debug   (io_dma_req_bits_status_debug),
    .io_deq_bits_cmd_status_cease   (io_dma_req_bits_status_cease),
    .io_deq_bits_cmd_status_wfi     (io_dma_req_bits_status_wfi),
    .io_deq_bits_cmd_status_isa     (io_dma_req_bits_status_isa),
    .io_deq_bits_cmd_status_dprv    (io_dma_req_bits_status_dprv),
    .io_deq_bits_cmd_status_dv      (io_dma_req_bits_status_dv),
    .io_deq_bits_cmd_status_prv     (io_dma_req_bits_status_prv),
    .io_deq_bits_cmd_status_v       (io_dma_req_bits_status_v),
    .io_deq_bits_cmd_status_sd      (io_dma_req_bits_status_sd),
    .io_deq_bits_cmd_status_zero2   (io_dma_req_bits_status_zero2),
    .io_deq_bits_cmd_status_mpv     (io_dma_req_bits_status_mpv),
    .io_deq_bits_cmd_status_gva     (io_dma_req_bits_status_gva),
    .io_deq_bits_cmd_status_mbe     (io_dma_req_bits_status_mbe),
    .io_deq_bits_cmd_status_sbe     (io_dma_req_bits_status_sbe),
    .io_deq_bits_cmd_status_sxl     (io_dma_req_bits_status_sxl),
    .io_deq_bits_cmd_status_uxl     (io_dma_req_bits_status_uxl),
    .io_deq_bits_cmd_status_sd_rv32 (io_dma_req_bits_status_sd_rv32),
    .io_deq_bits_cmd_status_zero1   (io_dma_req_bits_status_zero1),
    .io_deq_bits_cmd_status_tsr     (io_dma_req_bits_status_tsr),
    .io_deq_bits_cmd_status_tw      (io_dma_req_bits_status_tw),
    .io_deq_bits_cmd_status_tvm     (io_dma_req_bits_status_tvm),
    .io_deq_bits_cmd_status_mxr     (io_dma_req_bits_status_mxr),
    .io_deq_bits_cmd_status_sum     (io_dma_req_bits_status_sum),
    .io_deq_bits_cmd_status_mprv    (io_dma_req_bits_status_mprv),
    .io_deq_bits_cmd_status_xs      (io_dma_req_bits_status_xs),
    .io_deq_bits_cmd_status_fs      (io_dma_req_bits_status_fs),
    .io_deq_bits_cmd_status_mpp     (io_dma_req_bits_status_mpp),
    .io_deq_bits_cmd_status_vs      (io_dma_req_bits_status_vs),
    .io_deq_bits_cmd_status_spp     (io_dma_req_bits_status_spp),
    .io_deq_bits_cmd_status_mpie    (io_dma_req_bits_status_mpie),
    .io_deq_bits_cmd_status_ube     (io_dma_req_bits_status_ube),
    .io_deq_bits_cmd_status_spie    (io_dma_req_bits_status_spie),
    .io_deq_bits_cmd_status_upie    (io_dma_req_bits_status_upie),
    .io_deq_bits_cmd_status_mie     (io_dma_req_bits_status_mie),
    .io_deq_bits_cmd_status_hie     (io_dma_req_bits_status_hie),
    .io_deq_bits_cmd_status_sie     (io_dma_req_bits_status_sie),
    .io_deq_bits_cmd_status_uie     (io_dma_req_bits_status_uie),
    .io_deq_bits_rob_id_bits        (_cmd_q_io_deq_bits_rob_id_bits)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  DMACommandTracker cmd_tracker (	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27]
    .clock                               (clock),
    .reset                               (reset),
    .io_alloc_valid                      (cmd_tracker_io_alloc_valid),	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:114:{71,84}]
    .io_alloc_ready                      (_cmd_tracker_io_alloc_ready),
    .io_alloc_bits_tag_rob_id            (_cmd_q_io_deq_bits_rob_id_bits),	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_alloc_bits_bytes_to_read         (_cmd_tracker_io_alloc_bits_bytes_to_read_T_4),	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:116:8]
    .io_alloc_bits_cmd_id                (_cmd_tracker_io_alloc_bits_cmd_id),
    .io_request_returned_valid           (io_dma_resp_valid),
    .io_request_returned_bits_bytes_read (io_dma_resp_bits_bytesRead[10:0]),	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:121:51]
    .io_request_returned_bits_cmd_id     (io_dma_resp_bits_cmd_id[0]),	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:120:47]
    .io_cmd_completed_ready              (io_completed_ready),
    .io_cmd_completed_valid              (io_completed_valid),
    .io_cmd_completed_bits_tag_rob_id    (io_completed_bits),
    .io_busy                             (_cmd_tracker_io_busy)
  );	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:94:27]
  assign io_dma_req_valid = io_dma_req_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :99:116, :100:49]
  assign io_dma_req_bits_vaddr = _cmd_q_io_deq_bits_cmd_rs1[39:0] + {36'h0, row_counter} * _GEN[state_id];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :40:28, :64:21, :76:37, :102:{34,48}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_is_acc_addr = _cmd_q_io_deq_bits_cmd_rs2[31];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_accumulate = _cmd_q_io_deq_bits_cmd_rs2[30];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_read_full_acc_row = _cmd_q_io_deq_bits_cmd_rs2[29];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_norm_cmd = _cmd_q_io_deq_bits_cmd_rs2[28:26];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_garbage = _cmd_q_io_deq_bits_cmd_rs2[25:15];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_garbage_bit = _cmd_q_io_deq_bits_cmd_rs2[14];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_laddr_data = _cmd_q_io_deq_bits_cmd_rs2[13:0] + {10'h0, row_counter};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :40:28, :45:43, generators/gemmini/src/main/scala/gemmini/LocalAddr.scala:51:25, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_cols = {9'h0, _cmd_q_io_deq_bits_cmd_rs2[38:32]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, :104:24, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_repeats = {11'h0, _io_dma_req_bits_repeats_T & (|_cmd_q_io_deq_bits_cmd_rs1) ? _cmd_q_io_deq_bits_cmd_rs2[52:48] - 5'h1 : 5'h0};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :45:43, :72:25, :76:37, :105:{27,33,49,69}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_scale = _GEN_1[state_id];	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :64:21, :107:25]
  assign io_dma_req_bits_has_acc_bitwidth = io_dma_req_bits_has_acc_bitwidth_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :108:78]
  assign io_dma_req_bits_all_zeros = ~(|_cmd_q_io_deq_bits_cmd_rs1);	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :72:25, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_dma_req_bits_block_stride = {2'h0, _GEN_0[state_id]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :64:21, :106:32]
  assign io_dma_req_bits_pixel_repeats = {3'h0, _GEN_3[state_id]};	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :64:21, :111:33]
  assign io_dma_req_bits_cmd_id = {7'h0, _cmd_id_T ? _cmd_tracker_io_alloc_bits_cmd_id : cmd_id_buf};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40, generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :94:27, :125:26, generators/gemmini/src/main/scala/gemmini/Util.scala:90:24, :91:8]
  assign io_busy = _cmd_q_io_deq_valid | _cmd_tracker_io_busy;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :94:27, :96:24, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_counter_event_signal_8 = io_counter_event_signal_8_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :100:19]
  assign io_counter_event_signal_9 = io_counter_event_signal_9_0;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :101:20]
  assign io_counter_event_signal_10 = io_dma_req_valid_0 & ~io_dma_req_ready;	// @[generators/gemmini/src/main/scala/gemmini/LoadController.scala:13:7, :99:116, :100:49, :182:{91,94}]
endmodule

