// Generated by CIRCT firtool-1.75.0
module MacUnit(	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:14:7]
  input  [7:0]  io_in_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  input  [7:0]  io_in_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  input  [31:0] io_in_c,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  output [19:0] io_out_d	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
);

  wire [15:0] _io_out_d_T = {{8{io_in_a[7]}}, io_in_a} * {{8{io_in_b[7]}}, io_in_b};	// @[generators/gemmini/src/main/scala/gemmini/Arithmetic.scala:93:49]
  assign io_out_d = {{4{_io_out_d_T[15]}}, _io_out_d_T} + io_in_c[19:0];	// @[generators/gemmini/src/main/scala/gemmini/Arithmetic.scala:93:{49,54}, generators/gemmini/src/main/scala/gemmini/PE.scala:14:7, :16:14]
endmodule

