/* Generated by Yosys 0.63+161 (git sha1 5fd39ff3e, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "./RTL/TileWithReset.sv:3.1-50.10" *)
module TileWithReset(clock, reset, io_in_a_0, io_in_b_0, io_in_d_0, io_in_control_0_dataflow, io_in_control_0_propagate, io_in_control_0_shift, io_in_id_0, io_in_last_0, io_out_a_0, io_out_c_0, io_out_b_0, io_out_control_0_dataflow, io_out_control_0_propagate, io_out_control_0_shift, io_out_id_0, io_out_last_0, io_in_valid_0, io_out_valid_0, io_bad_dataflow);
  (* src = "./RTL/TileWithReset.sv:4.17-4.22" *)
  input clock;
  wire clock;
  (* src = "./RTL/TileWithReset.sv:5.17-5.22" *)
  input reset;
  wire reset;
  (* src = "./RTL/TileWithReset.sv:6.17-6.26" *)
  input [7:0] io_in_a_0;
  wire [7:0] io_in_a_0;
  (* src = "./RTL/TileWithReset.sv:7.17-7.26" *)
  input [19:0] io_in_b_0;
  wire [19:0] io_in_b_0;
  (* src = "./RTL/TileWithReset.sv:8.17-8.26" *)
  input [19:0] io_in_d_0;
  wire [19:0] io_in_d_0;
  (* src = "./RTL/TileWithReset.sv:9.17-9.41" *)
  input io_in_control_0_dataflow;
  wire io_in_control_0_dataflow;
  (* src = "./RTL/TileWithReset.sv:10.17-10.42" *)
  input io_in_control_0_propagate;
  wire io_in_control_0_propagate;
  (* src = "./RTL/TileWithReset.sv:11.17-11.38" *)
  input [4:0] io_in_control_0_shift;
  wire [4:0] io_in_control_0_shift;
  (* src = "./RTL/TileWithReset.sv:12.17-12.27" *)
  input [2:0] io_in_id_0;
  wire [2:0] io_in_id_0;
  (* src = "./RTL/TileWithReset.sv:13.17-13.29" *)
  input io_in_last_0;
  wire io_in_last_0;
  (* src = "./RTL/TileWithReset.sv:14.17-14.27" *)
  output [7:0] io_out_a_0;
  wire [7:0] io_out_a_0;
  (* src = "./RTL/TileWithReset.sv:15.17-15.27" *)
  output [19:0] io_out_c_0;
  wire [19:0] io_out_c_0;
  (* src = "./RTL/TileWithReset.sv:16.17-16.27" *)
  output [19:0] io_out_b_0;
  wire [19:0] io_out_b_0;
  (* src = "./RTL/TileWithReset.sv:17.17-17.42" *)
  output io_out_control_0_dataflow;
  wire io_out_control_0_dataflow;
  (* src = "./RTL/TileWithReset.sv:18.17-18.43" *)
  output io_out_control_0_propagate;
  wire io_out_control_0_propagate;
  (* src = "./RTL/TileWithReset.sv:19.17-19.39" *)
  output [4:0] io_out_control_0_shift;
  wire [4:0] io_out_control_0_shift;
  (* src = "./RTL/TileWithReset.sv:20.17-20.28" *)
  output [2:0] io_out_id_0;
  wire [2:0] io_out_id_0;
  (* src = "./RTL/TileWithReset.sv:21.17-21.30" *)
  output io_out_last_0;
  wire io_out_last_0;
  (* src = "./RTL/TileWithReset.sv:22.17-22.30" *)
  input io_in_valid_0;
  wire io_in_valid_0;
  (* src = "./RTL/TileWithReset.sv:23.17-23.31" *)
  output io_out_valid_0;
  wire io_out_valid_0;
  (* src = "./RTL/TileWithReset.sv:24.17-24.32" *)
  output io_bad_dataflow;
  wire io_bad_dataflow;
  (* src = "./RTL/PE_256.sv:127.72-127.105" *)
  wire [31:0] _00_;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  wire [31:0] _01_;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  wire [31:0] _02_;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  wire _03_;
  (* src = "./RTL/PE_256.sv:78.135-78.163" *)
  wire [31:0] _04_;
  (* src = "./RTL/PE_256.sv:78.53-78.183" *)
  wire _05_;
  (* src = "./RTL/PE_256.sv:78.53-78.98" *)
  wire _06_;
  (* src = "./RTL/PE_256.sv:82.57-82.102" *)
  wire _07_;
  (* src = "./RTL/PE_256.sv:82.139-82.169" *)
  wire [31:0] _08_;
  (* src = "./RTL/PE_256.sv:82.57-82.192" *)
  wire _09_;
  (* src = "./RTL/PE_256.sv:88.13-88.61" *)
  wire _10_;
  (* src = "./RTL/PE_256.sv:73.30-73.63" *)
  wire _11_;
  (* src = "./RTL/PE_256.sv:132.123-132.158" *)
  wire _12_;
  (* src = "./RTL/PE_256.sv:132.247-132.283" *)
  wire _13_;
  (* src = "./RTL/PE_256.sv:132.173-132.209" *)
  wire _14_;
  (* src = "./RTL/PE_256.sv:132.298-132.335" *)
  wire _15_;
  (* src = "./RTL/PE_256.sv:78.105-78.124" *)
  wire _16_;
  (* src = "./RTL/PE_256.sv:90.13-90.36" *)
  wire _17_;
  (* src = "./RTL/PE_256.sv:78.102-78.182" *)
  wire _18_;
  (* src = "./RTL/PE_256.sv:82.106-82.191" *)
  wire _19_;
  (* src = "./RTL/PE_256.sv:90.13-90.62" *)
  wire _20_;
  wire [31:0] _21_;
  wire [31:0] _22_;
  wire [31:0] _23_;
  wire [31:0] _24_;
  (* src = "./RTL/PE_256.sv:78.103-78.164" *)
  wire _25_;
  (* src = "./RTL/PE_256.sv:78.54-78.67" *)
  wire _26_;
  (* src = "./RTL/PE_256.sv:82.107-82.170" *)
  wire _27_;
  (* src = "./RTL/PE_256.sv:78.141-78.154" *)
  wire [31:0] _28_;
  (* src = "./RTL/PE_256.sv:78.140-78.163" *)
  wire [31:0] _29_;
  (* src = "./RTL/PE_256.sv:126.42-126.85" *)
  wire [7:0] _30_;
  (* src = "./RTL/PE_256.sv:132.47-132.92" *)
  wire [19:0] _31_;
  (* src = "./RTL/PE_256.sv:132.173-132.243" *)
  wire [19:0] _32_;
  (* src = "./RTL/PE_256.sv:132.123-132.243" *)
  wire [19:0] _33_;
  (* src = "./RTL/PE_256.sv:132.298-132.370" *)
  wire [19:0] _34_;
  (* src = "./RTL/PE_256.sv:132.247-132.370" *)
  wire [19:0] _35_;
  (* src = "./RTL/PE_256.sv:132.96-132.370" *)
  wire [19:0] _36_;
  (* src = "./RTL/PE_256.sv:78.105-78.163" *)
  wire [31:0] _37_;
  (* src = "./RTL/PE_256.sv:82.109-82.169" *)
  wire [31:0] _38_;
  (* src = "./RTL/PE_256.sv:96.15-96.78" *)
  wire [31:0] _39_;
  (* src = "./RTL/PE_256.sv:97.15-97.78" *)
  wire [31:0] _40_;
  (* hdlname = "tile_inst clock" *)
  (* src = "./RTL/Tile.sv:3.17-3.22" *)
  wire \tile_inst.clock ;
  (* hdlname = "tile_inst io_bad_dataflow" *)
  (* src = "./RTL/Tile.sv:22.17-22.32" *)
  wire \tile_inst.io_bad_dataflow ;
  (* hdlname = "tile_inst io_in_a_0" *)
  (* src = "./RTL/Tile.sv:4.17-4.26" *)
  wire [7:0] \tile_inst.io_in_a_0 ;
  (* hdlname = "tile_inst io_in_b_0" *)
  (* src = "./RTL/Tile.sv:5.17-5.26" *)
  wire [19:0] \tile_inst.io_in_b_0 ;
  (* hdlname = "tile_inst io_in_control_0_dataflow" *)
  (* src = "./RTL/Tile.sv:7.17-7.41" *)
  wire \tile_inst.io_in_control_0_dataflow ;
  (* hdlname = "tile_inst io_in_control_0_propagate" *)
  (* src = "./RTL/Tile.sv:8.17-8.42" *)
  wire \tile_inst.io_in_control_0_propagate ;
  (* hdlname = "tile_inst io_in_control_0_shift" *)
  (* src = "./RTL/Tile.sv:9.17-9.38" *)
  wire [4:0] \tile_inst.io_in_control_0_shift ;
  (* hdlname = "tile_inst io_in_d_0" *)
  (* src = "./RTL/Tile.sv:6.17-6.26" *)
  wire [19:0] \tile_inst.io_in_d_0 ;
  (* hdlname = "tile_inst io_in_id_0" *)
  (* src = "./RTL/Tile.sv:10.17-10.27" *)
  wire [2:0] \tile_inst.io_in_id_0 ;
  (* hdlname = "tile_inst io_in_last_0" *)
  (* src = "./RTL/Tile.sv:11.17-11.29" *)
  wire \tile_inst.io_in_last_0 ;
  (* hdlname = "tile_inst io_in_valid_0" *)
  (* src = "./RTL/Tile.sv:20.17-20.30" *)
  wire \tile_inst.io_in_valid_0 ;
  (* hdlname = "tile_inst io_out_a_0" *)
  (* src = "./RTL/Tile.sv:12.17-12.27" *)
  wire [7:0] \tile_inst.io_out_a_0 ;
  (* hdlname = "tile_inst io_out_b_0" *)
  (* src = "./RTL/Tile.sv:14.17-14.27" *)
  wire [19:0] \tile_inst.io_out_b_0 ;
  (* hdlname = "tile_inst io_out_c_0" *)
  (* src = "./RTL/Tile.sv:13.17-13.27" *)
  wire [19:0] \tile_inst.io_out_c_0 ;
  (* hdlname = "tile_inst io_out_control_0_dataflow" *)
  (* src = "./RTL/Tile.sv:15.17-15.42" *)
  wire \tile_inst.io_out_control_0_dataflow ;
  (* hdlname = "tile_inst io_out_control_0_propagate" *)
  (* src = "./RTL/Tile.sv:16.17-16.43" *)
  wire \tile_inst.io_out_control_0_propagate ;
  (* hdlname = "tile_inst io_out_control_0_shift" *)
  (* src = "./RTL/Tile.sv:17.17-17.39" *)
  wire [4:0] \tile_inst.io_out_control_0_shift ;
  (* hdlname = "tile_inst io_out_id_0" *)
  (* src = "./RTL/Tile.sv:18.17-18.28" *)
  wire [2:0] \tile_inst.io_out_id_0 ;
  (* hdlname = "tile_inst io_out_last_0" *)
  (* src = "./RTL/Tile.sv:19.17-19.30" *)
  wire \tile_inst.io_out_last_0 ;
  (* hdlname = "tile_inst io_out_valid_0" *)
  (* src = "./RTL/Tile.sv:21.17-21.31" *)
  wire \tile_inst.io_out_valid_0 ;
  (* hdlname = "tile_inst tile_0_0 _GEN" *)
  (* src = "./RTL/PE_256.sv:74.15-74.19" *)
  wire [31:0] \tile_inst.tile_0_0._GEN ;
  (* hdlname = "tile_inst tile_0_0 _GEN_0" *)
  (* src = "./RTL/PE_256.sv:76.15-76.21" *)
  wire [31:0] \tile_inst.tile_0_0._GEN_0 ;
  (* hdlname = "tile_inst tile_0_0 _GEN_1" *)
  (* src = "./RTL/PE_256.sv:79.15-79.21" *)
  wire [31:0] \tile_inst.tile_0_0._GEN_1 ;
  (* hdlname = "tile_inst tile_0_0 _GEN_2" *)
  (* src = "./RTL/PE_256.sv:83.15-83.21" *)
  wire [31:0] \tile_inst.tile_0_0._GEN_2 ;
  (* hdlname = "tile_inst tile_0_0 _GEN_3" *)
  (* src = "./RTL/PE_256.sv:84.15-84.21" *)
  wire [31:0] \tile_inst.tile_0_0._GEN_3 ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_T" *)
  (* src = "./RTL/PE_256.sv:77.15-77.26" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_T ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_T_11" *)
  (* src = "./RTL/PE_256.sv:81.15-81.29" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_T_11 ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_T_13" *)
  (* src = "./RTL/PE_256.sv:82.15-82.29" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_T_13 ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_T_2" *)
  (* src = "./RTL/PE_256.sv:78.15-78.28" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_T_2 ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_point_five_T_3" *)
  (* src = "./RTL/PE_256.sv:75.15-75.39" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_point_five_T_3 ;
  (* hdlname = "tile_inst tile_0_0 _io_out_c_point_five_T_8" *)
  (* src = "./RTL/PE_256.sv:80.15-80.39" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \tile_inst.tile_0_0._io_out_c_point_five_T_8 ;
  (* hdlname = "tile_inst tile_0_0 _mac_unit_io_out_d" *)
  (* src = "./RTL/PE_256.sv:69.15-69.33" *)
  wire [19:0] \tile_inst.tile_0_0._mac_unit_io_out_d ;
  (* hdlname = "tile_inst tile_0_0 c1" *)
  (* src = "./RTL/PE_256.sv:70.15-70.17" *)
  reg [31:0] \tile_inst.tile_0_0.c1 ;
  (* hdlname = "tile_inst tile_0_0 c2" *)
  (* src = "./RTL/PE_256.sv:71.15-71.17" *)
  reg [31:0] \tile_inst.tile_0_0.c2 ;
  (* hdlname = "tile_inst tile_0_0 clock" *)
  (* src = "./RTL/PE_256.sv:47.17-47.22" *)
  wire \tile_inst.tile_0_0.clock ;
  (* hdlname = "tile_inst tile_0_0 io_bad_dataflow" *)
  (* src = "./RTL/PE_256.sv:66.17-66.32" *)
  wire \tile_inst.tile_0_0.io_bad_dataflow ;
  (* hdlname = "tile_inst tile_0_0 io_in_a" *)
  (* src = "./RTL/PE_256.sv:48.17-48.24" *)
  wire [7:0] \tile_inst.tile_0_0.io_in_a ;
  (* hdlname = "tile_inst tile_0_0 io_in_b" *)
  (* src = "./RTL/PE_256.sv:49.17-49.24" *)
  wire [19:0] \tile_inst.tile_0_0.io_in_b ;
  (* hdlname = "tile_inst tile_0_0 io_in_control_dataflow" *)
  (* src = "./RTL/PE_256.sv:54.17-54.39" *)
  wire \tile_inst.tile_0_0.io_in_control_dataflow ;
  (* hdlname = "tile_inst tile_0_0 io_in_control_propagate" *)
  (* src = "./RTL/PE_256.sv:55.17-55.40" *)
  wire \tile_inst.tile_0_0.io_in_control_propagate ;
  (* hdlname = "tile_inst tile_0_0 io_in_control_shift" *)
  (* src = "./RTL/PE_256.sv:56.17-56.36" *)
  wire [4:0] \tile_inst.tile_0_0.io_in_control_shift ;
  (* hdlname = "tile_inst tile_0_0 io_in_d" *)
  (* src = "./RTL/PE_256.sv:50.17-50.24" *)
  wire [19:0] \tile_inst.tile_0_0.io_in_d ;
  (* hdlname = "tile_inst tile_0_0 io_in_id" *)
  (* src = "./RTL/PE_256.sv:60.17-60.25" *)
  wire [2:0] \tile_inst.tile_0_0.io_in_id ;
  (* hdlname = "tile_inst tile_0_0 io_in_last" *)
  (* src = "./RTL/PE_256.sv:62.17-62.27" *)
  wire \tile_inst.tile_0_0.io_in_last ;
  (* hdlname = "tile_inst tile_0_0 io_in_valid" *)
  (* src = "./RTL/PE_256.sv:64.17-64.28" *)
  wire \tile_inst.tile_0_0.io_in_valid ;
  (* hdlname = "tile_inst tile_0_0 io_out_a" *)
  (* src = "./RTL/PE_256.sv:51.17-51.25" *)
  wire [7:0] \tile_inst.tile_0_0.io_out_a ;
  (* hdlname = "tile_inst tile_0_0 io_out_b" *)
  (* src = "./RTL/PE_256.sv:52.17-52.25" *)
  wire [19:0] \tile_inst.tile_0_0.io_out_b ;
  (* hdlname = "tile_inst tile_0_0 io_out_c" *)
  (* src = "./RTL/PE_256.sv:53.17-53.25" *)
  wire [19:0] \tile_inst.tile_0_0.io_out_c ;
  (* hdlname = "tile_inst tile_0_0 io_out_control_dataflow" *)
  (* src = "./RTL/PE_256.sv:57.17-57.40" *)
  wire \tile_inst.tile_0_0.io_out_control_dataflow ;
  (* hdlname = "tile_inst tile_0_0 io_out_control_propagate" *)
  (* src = "./RTL/PE_256.sv:58.17-58.41" *)
  wire \tile_inst.tile_0_0.io_out_control_propagate ;
  (* hdlname = "tile_inst tile_0_0 io_out_control_shift" *)
  (* src = "./RTL/PE_256.sv:59.17-59.37" *)
  wire [4:0] \tile_inst.tile_0_0.io_out_control_shift ;
  (* hdlname = "tile_inst tile_0_0 io_out_id" *)
  (* src = "./RTL/PE_256.sv:61.17-61.26" *)
  wire [2:0] \tile_inst.tile_0_0.io_out_id ;
  (* hdlname = "tile_inst tile_0_0 io_out_last" *)
  (* src = "./RTL/PE_256.sv:63.17-63.28" *)
  wire \tile_inst.tile_0_0.io_out_last ;
  (* hdlname = "tile_inst tile_0_0 io_out_valid" *)
  (* src = "./RTL/PE_256.sv:65.17-65.29" *)
  wire \tile_inst.tile_0_0.io_out_valid ;
  (* hdlname = "tile_inst tile_0_0 last_s" *)
  (* src = "./RTL/PE_256.sv:72.15-72.21" *)
  reg \tile_inst.tile_0_0.last_s ;
  (* hdlname = "tile_inst tile_0_0 mac_unit _io_out_d_T" *)
  (* src = "./RTL/MacUnit.sv:9.15-9.26" *)
  wire [15:0] \tile_inst.tile_0_0.mac_unit._io_out_d_T ;
  (* hdlname = "tile_inst tile_0_0 mac_unit io_in_a" *)
  (* src = "./RTL/MacUnit.sv:3.17-3.24" *)
  wire [7:0] \tile_inst.tile_0_0.mac_unit.io_in_a ;
  (* hdlname = "tile_inst tile_0_0 mac_unit io_in_b" *)
  (* src = "./RTL/MacUnit.sv:4.17-4.24" *)
  wire [7:0] \tile_inst.tile_0_0.mac_unit.io_in_b ;
  (* hdlname = "tile_inst tile_0_0 mac_unit io_in_c" *)
  (* src = "./RTL/MacUnit.sv:5.17-5.24" *)
  wire [31:0] \tile_inst.tile_0_0.mac_unit.io_in_c ;
  (* hdlname = "tile_inst tile_0_0 mac_unit io_out_d" *)
  (* src = "./RTL/MacUnit.sv:6.17-6.25" *)
  wire [19:0] \tile_inst.tile_0_0.mac_unit.io_out_d ;
  (* hdlname = "tile_inst tile_0_0 shift_offset" *)
  (* src = "./RTL/PE_256.sv:73.15-73.27" *)
  wire [4:0] \tile_inst.tile_0_0.shift_offset ;
  assign \tile_inst.tile_0_0._io_out_c_T_2  = \tile_inst.tile_0_0._io_out_c_T  + (* src = "./RTL/PE_256.sv:78.31-78.184" *) _05_;
  assign \tile_inst.tile_0_0._io_out_c_T_13  = \tile_inst.tile_0_0._io_out_c_T_11  + (* src = "./RTL/PE_256.sv:82.32-82.193" *) _09_;
  assign _04_ = \tile_inst.tile_0_0.c1  & (* src = "./RTL/PE_256.sv:78.135-78.163" *) _29_;
  assign _05_ = _06_ & (* src = "./RTL/PE_256.sv:78.53-78.183" *) _18_;
  assign _06_ = _26_ & (* src = "./RTL/PE_256.sv:78.53-78.98" *) \tile_inst.tile_0_0._io_out_c_point_five_T_3 [0];
  assign _07_ = _26_ & (* src = "./RTL/PE_256.sv:82.57-82.102" *) \tile_inst.tile_0_0._io_out_c_point_five_T_8 [0];
  assign _08_ = \tile_inst.tile_0_0.c2  & (* src = "./RTL/PE_256.sv:82.139-82.169" *) _29_;
  assign _09_ = _07_ & (* src = "./RTL/PE_256.sv:82.57-82.192" *) _19_;
  assign _10_ = io_in_control_0_dataflow & (* src = "./RTL/PE_256.sv:88.13-88.61" *) io_in_control_0_propagate;
  assign _11_ = \tile_inst.tile_0_0.last_s  == (* src = "./RTL/PE_256.sv:73.30-73.63" *) io_in_control_0_propagate;
  assign _12_ = $signed(\tile_inst.tile_0_0._io_out_c_T_2 ) > (* src = "./RTL/PE_256.sv:132.123-132.158" *) $signed(20'h7ffff);
  assign _13_ = $signed(\tile_inst.tile_0_0._io_out_c_T_13 ) > (* src = "./RTL/PE_256.sv:132.247-132.283" *) $signed(20'h7ffff);
  assign _14_ = $signed(\tile_inst.tile_0_0._io_out_c_T_2 ) < (* src = "./RTL/PE_256.sv:132.173-132.209" *) $signed(20'h80000);
  assign _15_ = $signed(\tile_inst.tile_0_0._io_out_c_T_13 ) < (* src = "./RTL/PE_256.sv:132.298-132.335" *) $signed(20'h80000);
  assign _16_ = \tile_inst.tile_0_0.shift_offset  < (* src = "./RTL/PE_256.sv:82.109-82.128" *) 2'h2;
  assign _17_ = ~ (* src = "./RTL/PE_256.sv:90.13-90.36" *) io_in_control_0_dataflow;
  assign _18_ = _25_ | (* src = "./RTL/PE_256.sv:78.102-78.182" *) \tile_inst.tile_0_0._io_out_c_T [0];
  assign _19_ = _27_ | (* src = "./RTL/PE_256.sv:82.106-82.191" *) \tile_inst.tile_0_0._io_out_c_T_11 [0];
  assign _20_ = _17_ | (* src = "./RTL/PE_256.sv:90.13-90.62" *) io_in_control_0_propagate;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  always @(posedge clock)
    \tile_inst.tile_0_0.c1  <= _01_;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  always @(posedge clock)
    \tile_inst.tile_0_0.c2  <= _02_;
  (* src = "./RTL/PE_256.sv:85.3-101.6" *)
  always @(posedge clock)
    \tile_inst.tile_0_0.last_s  <= _03_;
  assign _03_ = io_in_valid_0 ? (* src = "./RTL/PE_256.sv:86.9-86.20|./RTL/PE_256.sv:86.5-100.8" *) io_in_control_0_propagate : \tile_inst.tile_0_0.last_s ;
  assign _21_ = _20_ ? (* full_case = 32'h00000001 *) (* src = "./RTL/PE_256.sv:90.13-90.62|./RTL/PE_256.sv:90.9-93.24" *) \tile_inst.tile_0_0.c2  : { io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0 };
  assign _22_ = io_in_control_0_dataflow ? (* full_case = 32'h00000001 *) (* src = "./RTL/PE_256.sv:87.11-87.33|./RTL/PE_256.sv:87.7-98.10" *) _21_ : _40_;
  assign _02_ = io_in_valid_0 ? (* src = "./RTL/PE_256.sv:86.9-86.20|./RTL/PE_256.sv:86.5-100.8" *) _22_ : \tile_inst.tile_0_0.c2 ;
  assign _23_ = _10_ ? (* src = "./RTL/PE_256.sv:88.13-88.61|./RTL/PE_256.sv:88.9-89.24" *) { io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0 } : \tile_inst.tile_0_0.c1 ;
  assign _24_ = io_in_control_0_dataflow ? (* full_case = 32'h00000001 *) (* src = "./RTL/PE_256.sv:87.11-87.33|./RTL/PE_256.sv:87.7-98.10" *) _23_ : _39_;
  assign _01_ = io_in_valid_0 ? (* src = "./RTL/PE_256.sv:86.9-86.20|./RTL/PE_256.sv:86.5-100.8" *) _24_ : \tile_inst.tile_0_0.c1 ;
  assign _25_ = | (* src = "./RTL/PE_256.sv:78.103-78.164" *) _37_;
  assign _26_ = | (* src = "./RTL/PE_256.sv:82.58-82.71" *) \tile_inst.tile_0_0.shift_offset ;
  assign _27_ = | (* src = "./RTL/PE_256.sv:82.107-82.170" *) _38_;
  assign _28_ = 1'h1 << (* src = "./RTL/PE_256.sv:82.145-82.160" *) \tile_inst.tile_0_0._GEN [4:0];
  assign \tile_inst.tile_0_0._io_out_c_point_five_T_3 [0] = $signed(\tile_inst.tile_0_0.c1 ) >>> (* src = "./RTL/PE_256.sv:75.50-75.70" *) \tile_inst.tile_0_0._GEN [4:0];
  assign \tile_inst.tile_0_0._io_out_c_T  = $signed(\tile_inst.tile_0_0.c1 ) >>> (* src = "./RTL/PE_256.sv:77.37-77.59" *) \tile_inst.tile_0_0.shift_offset ;
  assign \tile_inst.tile_0_0._io_out_c_point_five_T_8 [0] = $signed(\tile_inst.tile_0_0.c2 ) >>> (* src = "./RTL/PE_256.sv:80.50-80.72" *) \tile_inst.tile_0_0._GEN [4:0];
  assign \tile_inst.tile_0_0._io_out_c_T_11  = $signed(\tile_inst.tile_0_0.c2 ) >>> (* src = "./RTL/PE_256.sv:81.40-81.62" *) \tile_inst.tile_0_0.shift_offset ;
  assign \tile_inst.tile_0_0._GEN [4:0] = \tile_inst.tile_0_0.shift_offset  - (* src = "./RTL/PE_256.sv:79.32-79.51" *) 1'h1;
  assign _29_ = _28_ - (* src = "./RTL/PE_256.sv:82.144-82.169" *) 1'h1;
  assign _30_ = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:126.42-126.85" *) \tile_inst.tile_0_0.c2 [7:0] : \tile_inst.tile_0_0.c1 [7:0];
  assign \tile_inst.tile_0_0.mac_unit.io_in_b  = io_in_control_0_dataflow ? (* src = "./RTL/PE_256.sv:126.16-126.101" *) _30_ : io_in_b_0[7:0];
  assign _00_[19:0] = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:127.72-127.105" *) \tile_inst.tile_0_0.c2 [19:0] : \tile_inst.tile_0_0.c1 [19:0];
  assign \tile_inst.tile_0_0.mac_unit.io_in_c [19:0] = io_in_control_0_dataflow ? (* src = "./RTL/PE_256.sv:127.16-127.105" *) io_in_b_0 : _00_[19:0];
  assign io_out_b_0 = io_in_control_0_dataflow ? (* src = "./RTL/PE_256.sv:131.21-131.74" *) \tile_inst.tile_0_0._mac_unit_io_out_d  : io_in_b_0;
  assign _31_ = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:132.47-132.92" *) \tile_inst.tile_0_0.c1 [19:0] : \tile_inst.tile_0_0.c2 [19:0];
  assign _32_ = _14_ ? (* src = "./RTL/PE_256.sv:132.173-132.243" *) 20'h80000 : \tile_inst.tile_0_0._io_out_c_T_2 [19:0];
  assign _33_ = _12_ ? (* src = "./RTL/PE_256.sv:132.123-132.243" *) 20'h7ffff : _32_;
  assign _34_ = _15_ ? (* src = "./RTL/PE_256.sv:132.298-132.370" *) 20'h80000 : \tile_inst.tile_0_0._io_out_c_T_13 [19:0];
  assign _35_ = _13_ ? (* src = "./RTL/PE_256.sv:132.247-132.370" *) 20'h7ffff : _34_;
  assign _36_ = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:132.96-132.370" *) _33_ : _35_;
  assign io_out_c_0 = io_in_control_0_dataflow ? (* src = "./RTL/PE_256.sv:132.21-132.370" *) _31_ : _36_;
  assign \tile_inst.tile_0_0.shift_offset  = _11_ ? (* src = "./RTL/PE_256.sv:73.30-73.92" *) 5'h00 : io_in_control_0_shift;
  assign _37_ = _16_ ? (* src = "./RTL/PE_256.sv:78.105-78.163" *) 32'h00000000 : _04_;
  assign _38_ = _16_ ? (* src = "./RTL/PE_256.sv:82.109-82.169" *) 32'h00000000 : _08_;
  assign _39_ = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:96.15-96.78" *) { io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0 } : { \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d  };
  assign _40_ = io_in_control_0_propagate ? (* src = "./RTL/PE_256.sv:97.15-97.78" *) { \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d  } : { io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0 };
  assign \tile_inst.tile_0_0._mac_unit_io_out_d  = { \tile_inst.tile_0_0.mac_unit._io_out_d_T [15], \tile_inst.tile_0_0.mac_unit._io_out_d_T [15], \tile_inst.tile_0_0.mac_unit._io_out_d_T [15], \tile_inst.tile_0_0.mac_unit._io_out_d_T [15], \tile_inst.tile_0_0.mac_unit._io_out_d_T  } + (* src = "./RTL/MacUnit.sv:10.21-10.72" *) \tile_inst.tile_0_0.mac_unit.io_in_c [19:0];
  assign \tile_inst.tile_0_0.mac_unit._io_out_d_T  = $signed(io_in_a_0) * (* src = "./RTL/MacUnit.sv:9.29-9.84" *) $signed(\tile_inst.tile_0_0.mac_unit.io_in_b );
  assign _00_[31:20] = 12'hxxx;
  assign io_bad_dataflow = 1'h0;
  assign io_out_a_0 = io_in_a_0;
  assign io_out_control_0_dataflow = io_in_control_0_dataflow;
  assign io_out_control_0_propagate = io_in_control_0_propagate;
  assign io_out_control_0_shift = io_in_control_0_shift;
  assign io_out_id_0 = io_in_id_0;
  assign io_out_last_0 = io_in_last_0;
  assign io_out_valid_0 = io_in_valid_0;
  assign \tile_inst.clock  = clock;
  assign \tile_inst.io_bad_dataflow  = 1'h0;
  assign \tile_inst.io_in_a_0  = io_in_a_0;
  assign \tile_inst.io_in_b_0  = io_in_b_0;
  assign \tile_inst.io_in_control_0_dataflow  = io_in_control_0_dataflow;
  assign \tile_inst.io_in_control_0_propagate  = io_in_control_0_propagate;
  assign \tile_inst.io_in_control_0_shift  = io_in_control_0_shift;
  assign \tile_inst.io_in_d_0  = io_in_d_0;
  assign \tile_inst.io_in_id_0  = io_in_id_0;
  assign \tile_inst.io_in_last_0  = io_in_last_0;
  assign \tile_inst.io_in_valid_0  = io_in_valid_0;
  assign \tile_inst.io_out_a_0  = io_in_a_0;
  assign \tile_inst.io_out_b_0  = io_out_b_0;
  assign \tile_inst.io_out_c_0  = io_out_c_0;
  assign \tile_inst.io_out_control_0_dataflow  = io_in_control_0_dataflow;
  assign \tile_inst.io_out_control_0_propagate  = io_in_control_0_propagate;
  assign \tile_inst.io_out_control_0_shift  = io_in_control_0_shift;
  assign \tile_inst.io_out_id_0  = io_in_id_0;
  assign \tile_inst.io_out_last_0  = io_in_last_0;
  assign \tile_inst.io_out_valid_0  = io_in_valid_0;
  assign \tile_inst.tile_0_0._GEN [31:5] = 27'h0000000;
  assign \tile_inst.tile_0_0._GEN_0  = { 27'h0000000, \tile_inst.tile_0_0.shift_offset  };
  assign \tile_inst.tile_0_0._GEN_1  = { 27'h0000000, \tile_inst.tile_0_0._GEN [4:0] };
  assign \tile_inst.tile_0_0._GEN_2  = { io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0[19], io_in_d_0 };
  assign \tile_inst.tile_0_0._GEN_3  = { \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d [19], \tile_inst.tile_0_0._mac_unit_io_out_d  };
  assign \tile_inst.tile_0_0.clock  = clock;
  assign \tile_inst.tile_0_0.io_bad_dataflow  = 1'h0;
  assign \tile_inst.tile_0_0.io_in_a  = io_in_a_0;
  assign \tile_inst.tile_0_0.io_in_b  = io_in_b_0;
  assign \tile_inst.tile_0_0.io_in_control_dataflow  = io_in_control_0_dataflow;
  assign \tile_inst.tile_0_0.io_in_control_propagate  = io_in_control_0_propagate;
  assign \tile_inst.tile_0_0.io_in_control_shift  = io_in_control_0_shift;
  assign \tile_inst.tile_0_0.io_in_d  = io_in_d_0;
  assign \tile_inst.tile_0_0.io_in_id  = io_in_id_0;
  assign \tile_inst.tile_0_0.io_in_last  = io_in_last_0;
  assign \tile_inst.tile_0_0.io_in_valid  = io_in_valid_0;
  assign \tile_inst.tile_0_0.io_out_a  = io_in_a_0;
  assign \tile_inst.tile_0_0.io_out_b  = io_out_b_0;
  assign \tile_inst.tile_0_0.io_out_c  = io_out_c_0;
  assign \tile_inst.tile_0_0.io_out_control_dataflow  = io_in_control_0_dataflow;
  assign \tile_inst.tile_0_0.io_out_control_propagate  = io_in_control_0_propagate;
  assign \tile_inst.tile_0_0.io_out_control_shift  = io_in_control_0_shift;
  assign \tile_inst.tile_0_0.io_out_id  = io_in_id_0;
  assign \tile_inst.tile_0_0.io_out_last  = io_in_last_0;
  assign \tile_inst.tile_0_0.io_out_valid  = io_in_valid_0;
  assign \tile_inst.tile_0_0.mac_unit.io_in_a  = io_in_a_0;
  assign \tile_inst.tile_0_0.mac_unit.io_in_c [31:20] = 12'hxxx;
  assign \tile_inst.tile_0_0.mac_unit.io_out_d  = \tile_inst.tile_0_0._mac_unit_io_out_d ;
endmodule
