// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PE(	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
  input        clock,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
  input  [7:0] io_inR,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
  input  [7:0] io_inD,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
  output [7:0] io_outL,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
  output [7:0] io_outU,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
  input        io_dir,	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
  input        io_en	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
);

  reg [7:0] reg_0;	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:110:24]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
    if (io_en)	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:101:16]
      reg_0 <= io_dir ? io_inD : io_inR;	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:110:{24,28}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][7:0];	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9, :110:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_outL = reg_0;	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9, :110:24]
  assign io_outU = reg_0;	// @[generators/gemmini/src/main/scala/gemmini/Transposer.scala:100:9, :110:24]
endmodule

