// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue5_ComputeCntlSignals(	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input         clock,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input         reset,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  output        io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_perform_mul_pre,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_perform_single_mul,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_perform_single_preload,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_a_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_b_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [1:0]  io_enq_bits_d_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_a_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_b_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_d_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_a_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_b_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_d_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_a_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_b_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_d_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_accumulate_zeros,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_preload_zeros,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_a_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_b_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_d_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_a_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_b_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_d_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_c_addr_is_acc_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_c_addr_accumulate,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_c_addr_read_full_acc_row,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [2:0]  io_enq_bits_c_addr_norm_cmd,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [10:0] io_enq_bits_c_addr_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_c_addr_garbage_bit,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [13:0] io_enq_bits_c_addr_data,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_c_rows,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_c_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_a_transpose,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_bd_transpose,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_total_rows,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_rob_id_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [5:0]  io_enq_bits_rob_id_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_dataflow,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_prop,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [4:0]  io_enq_bits_shift,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_enq_bits_first,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input         io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_perform_single_mul,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_perform_single_preload,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_a_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_b_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [1:0]  io_deq_bits_d_bank,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_a_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_b_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_d_bank_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_a_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_b_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_d_read_from_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_a_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_b_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_d_garbage,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_accumulate_zeros,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_preload_zeros,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_a_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_b_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_d_fire,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_a_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_b_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_d_unpadded_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_c_addr_is_acc_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_c_addr_accumulate,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_c_addr_read_full_acc_row,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_c_addr_garbage_bit,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [13:0] io_deq_bits_c_addr_data,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_c_rows,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_c_cols,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_a_transpose,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_bd_transpose,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_total_rows,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_rob_id_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [5:0]  io_deq_bits_rob_id_bits,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_dataflow,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_prop,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [4:0]  io_deq_bits_shift,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_im2colling,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output        io_deq_bits_first	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
);

  wire        io_enq_ready_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:286:16, :306:{24,39}]
  wire [87:0] _ram_ext_R0_data;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  reg  [2:0]  enq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg  [2:0]  deq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
  wire        ptr_match = enq_ptr_value == deq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33]
  wire        empty = ptr_match & ~maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :261:{25,28}]
  wire        do_enq = io_enq_ready_0 & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :286:16, :306:{24,39}]
  assign io_enq_ready_0 = io_deq_ready | ~(ptr_match & maybe_full);	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24, :286:{16,19}, :306:{24,39}]
  wire        do_deq = io_deq_ready & ~empty;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :261:25, :285:19]
  always @(posedge clock) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    if (reset) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      enq_ptr_value <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      deq_ptr_value <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      maybe_full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        enq_ptr_value <= enq_ptr_value == 3'h4 ? 3'h0 : enq_ptr_value + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, :77:{15,24}, :87:{20,28}]
      if (do_deq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        deq_ptr_value <= deq_ptr_value == 3'h4 ? 3'h0 : deq_ptr_value + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, :77:{15,24}, :87:{20,28}]
      if (~(do_enq == do_deq))	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16]
        maybe_full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_5x88 ram_ext (	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
    .R0_addr (deq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .W0_en   (do_enq),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_first, 1'h0, io_enq_bits_shift, io_enq_bits_prop, io_enq_bits_dataflow, io_enq_bits_rob_id_bits, io_enq_bits_rob_id_valid, io_enq_bits_total_rows, io_enq_bits_bd_transpose, io_enq_bits_a_transpose, io_enq_bits_c_cols, io_enq_bits_c_rows, io_enq_bits_c_addr_data, io_enq_bits_c_addr_garbage_bit, io_enq_bits_c_addr_read_full_acc_row, io_enq_bits_c_addr_accumulate, io_enq_bits_c_addr_is_acc_addr, io_enq_bits_d_unpadded_cols, io_enq_bits_b_unpadded_cols, io_enq_bits_a_unpadded_cols, io_enq_bits_d_fire, io_enq_bits_b_fire, io_enq_bits_a_fire, io_enq_bits_preload_zeros, io_enq_bits_accumulate_zeros, io_enq_bits_d_garbage, io_enq_bits_b_garbage, io_enq_bits_a_garbage, io_enq_bits_d_read_from_acc, io_enq_bits_b_read_from_acc, io_enq_bits_a_read_from_acc, io_enq_bits_d_bank_acc, io_enq_bits_b_bank_acc, io_enq_bits_a_bank_acc, io_enq_bits_d_bank, io_enq_bits_b_bank, io_enq_bits_a_bank, io_enq_bits_perform_single_preload, io_enq_bits_perform_single_mul})	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  assign io_enq_ready = io_enq_ready_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :286:16, :306:{24,39}]
  assign io_deq_valid = ~empty;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :261:25, :285:19]
  assign io_deq_bits_perform_single_mul = _ram_ext_R0_data[0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_perform_single_preload = _ram_ext_R0_data[1];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_bank = _ram_ext_R0_data[3:2];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_bank = _ram_ext_R0_data[5:4];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_bank = _ram_ext_R0_data[7:6];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_bank_acc = _ram_ext_R0_data[8];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_bank_acc = _ram_ext_R0_data[9];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_bank_acc = _ram_ext_R0_data[10];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_read_from_acc = _ram_ext_R0_data[11];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_read_from_acc = _ram_ext_R0_data[12];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_read_from_acc = _ram_ext_R0_data[13];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_garbage = _ram_ext_R0_data[14];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_garbage = _ram_ext_R0_data[15];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_garbage = _ram_ext_R0_data[16];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_accumulate_zeros = _ram_ext_R0_data[17];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_preload_zeros = _ram_ext_R0_data[18];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_fire = _ram_ext_R0_data[19];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_fire = _ram_ext_R0_data[20];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_fire = _ram_ext_R0_data[21];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_unpadded_cols = _ram_ext_R0_data[26:22];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_b_unpadded_cols = _ram_ext_R0_data[31:27];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_d_unpadded_cols = _ram_ext_R0_data[36:32];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_addr_is_acc_addr = _ram_ext_R0_data[37];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_addr_accumulate = _ram_ext_R0_data[38];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_addr_read_full_acc_row = _ram_ext_R0_data[39];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_addr_garbage_bit = _ram_ext_R0_data[40];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_addr_data = _ram_ext_R0_data[54:41];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_rows = _ram_ext_R0_data[59:55];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_c_cols = _ram_ext_R0_data[64:60];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_a_transpose = _ram_ext_R0_data[65];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_bd_transpose = _ram_ext_R0_data[66];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_total_rows = _ram_ext_R0_data[71:67];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_rob_id_valid = _ram_ext_R0_data[72];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_rob_id_bits = _ram_ext_R0_data[78:73];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_dataflow = _ram_ext_R0_data[79];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_prop = _ram_ext_R0_data[80];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_shift = _ram_ext_R0_data[85:81];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_im2colling = _ram_ext_R0_data[86];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_first = _ram_ext_R0_data[87];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
endmodule

