// Generated by CIRCT firtool-1.75.0
module Tile(	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:16:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:16:7]
  input  [7:0]  io_in_a_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input  [19:0] io_in_b_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input  [19:0] io_in_d_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input         io_in_control_0_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input         io_in_control_0_propagate,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input  [4:0]  io_in_control_0_shift,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input  [2:0]  io_in_id_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input         io_in_last_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [7:0]  io_out_a_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [19:0] io_out_c_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [19:0] io_out_b_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output        io_out_control_0_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output        io_out_control_0_propagate,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [4:0]  io_out_control_0_shift,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output [2:0]  io_out_id_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output        io_out_last_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  input         io_in_valid_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output        io_out_valid_0,	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
  output        io_bad_dataflow	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:17:14]
);

  PE_256 tile_0_0 (	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:42:44]
    .clock                    (clock),
    .io_in_a                  (io_in_a_0),
    .io_in_b                  (io_in_b_0),
    .io_in_d                  (io_in_d_0),
    .io_out_a                 (io_out_a_0),
    .io_out_b                 (io_out_b_0),
    .io_out_c                 (io_out_c_0),
    .io_in_control_dataflow   (io_in_control_0_dataflow),
    .io_in_control_propagate  (io_in_control_0_propagate),
    .io_in_control_shift      (io_in_control_0_shift),
    .io_out_control_dataflow  (io_out_control_0_dataflow),
    .io_out_control_propagate (io_out_control_0_propagate),
    .io_out_control_shift     (io_out_control_0_shift),
    .io_in_id                 (io_in_id_0),
    .io_out_id                (io_out_id_0),
    .io_in_last               (io_in_last_0),
    .io_out_last              (io_out_last_0),
    .io_in_valid              (io_in_valid_0),
    .io_out_valid             (io_out_valid_0),
    .io_bad_dataflow          (io_bad_dataflow)
  );	// @[generators/gemmini/src/main/scala/gemmini/Tile.scala:42:44]
endmodule

