// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TransposePreloadUnroller(	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
  output        io_in_ready,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input  [6:0]  io_in_bits_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input  [63:0] io_in_bits_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input  [63:0] io_in_bits_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input  [5:0]  io_in_bits_rob_id_bits,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  input         io_out_ready,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output        io_out_valid,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output [6:0]  io_out_bits_cmd_inst_funct,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output [63:0] io_out_bits_cmd_rs1,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output [63:0] io_out_bits_cmd_rs2,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output        io_out_bits_rob_id_valid,	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
  output [5:0]  io_out_bits_rob_id_bits	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:14:14]
);

  wire        _q_io_deq_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire        _q_io_deq_valid_1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [6:0]  _q_io_deq_bits_0_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_0_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_0_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [5:0]  _q_io_deq_bits_0_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [6:0]  _q_io_deq_bits_1_cmd_inst_funct;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_1_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_1_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  wire [5:0]  _q_io_deq_bits_1_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  reg  [1:0]  state;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22]
  wire        _state_T = state == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :35:71]
  wire        first_preload = _q_io_deq_valid_0 & _q_io_deq_bits_0_cmd_inst_funct == 7'h6 & _state_T;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:35:{33,46,62,71}]
  reg         b_transposed_and_ws;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:37:32]
  wire        io_out_valid_0 = first_preload ? ~b_transposed_and_ws | _q_io_deq_valid_1 : state[1] | _q_io_deq_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :35:{33,62}, :37:32, :57:{23,44}, :58:12, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _q_io_deq_pop_T_1 = first_preload & b_transposed_and_ws & _q_io_deq_valid_1 & _q_io_deq_bits_1_cmd_inst_funct == 7'h4;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:35:{33,62}, :37:32, :38:{44,57,70}, :62:20]
  wire        _state_T_1 = state == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :58:12, :63:12]
  wire        _GEN = _q_io_deq_pop_T_1 | ~_state_T_1;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:38:{44,57}, :62:20, :63:12, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _q_io_deq_pop_T = io_out_ready & io_out_valid_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        is_config = _q_io_deq_bits_0_cmd_inst_funct == 7'h0 & _q_io_deq_bits_0_cmd_rs1[1:0] == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:53:40, :54:{29,44,63}]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
    if (reset)	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
      state <= 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22]
    else if (~_q_io_deq_pop_T | is_config) begin	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :54:44, :69:22, :70:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    else if (_q_io_deq_pop_T_1)	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:38:{44,57}, :62:20]
      state <= 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :58:12]
    else if (|state)	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :77:23]
      state <= _state_T ? 2'h1 : {_state_T_1, 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :25:22, :35:71, :58:12, :63:12, :78:22]
    if (_q_io_deq_pop_T & is_config & ~(_q_io_deq_bits_0_cmd_rs1[7]))	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:37:32, :54:44, :69:22, :70:22, :71:45, :72:{13,32}, :73:29, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      b_transposed_and_ws <= _q_io_deq_bits_0_cmd_rs1[2] & _q_io_deq_bits_0_cmd_rs1[9];	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:37:32, :73:{79,105,123}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
        state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :25:22]
        b_transposed_and_ws = _RANDOM[/*Zero width*/ 1'b0][2];	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :25:22, :37:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MultiHeadedQueue q (	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (io_in_ready),
    .io_enq_valid                 (io_in_valid),
    .io_enq_bits_cmd_inst_funct   (io_in_bits_cmd_inst_funct),
    .io_enq_bits_cmd_rs1          (io_in_bits_cmd_rs1),
    .io_enq_bits_cmd_rs2          (io_in_bits_cmd_rs2),
    .io_enq_bits_rob_id_bits      (io_in_bits_rob_id_bits),
    .io_deq_valid_0               (_q_io_deq_valid_0),
    .io_deq_valid_1               (_q_io_deq_valid_1),
    .io_deq_bits_0_cmd_inst_funct (_q_io_deq_bits_0_cmd_inst_funct),
    .io_deq_bits_0_cmd_rs1        (_q_io_deq_bits_0_cmd_rs1),
    .io_deq_bits_0_cmd_rs2        (_q_io_deq_bits_0_cmd_rs2),
    .io_deq_bits_0_rob_id_bits    (_q_io_deq_bits_0_rob_id_bits),
    .io_deq_bits_1_cmd_inst_funct (_q_io_deq_bits_1_cmd_inst_funct),
    .io_deq_bits_1_cmd_rs1        (_q_io_deq_bits_1_cmd_rs1),
    .io_deq_bits_1_cmd_rs2        (_q_io_deq_bits_1_cmd_rs2),
    .io_deq_bits_1_rob_id_bits    (_q_io_deq_bits_1_rob_id_bits),
    .io_deq_pop                   (_q_io_deq_pop_T & ~_q_io_deq_pop_T_1 & state != 2'h1)	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:25:22, :38:{44,57}, :58:12, :62:20, :67:{28,31,66,75}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  );	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19]
  assign io_out_valid = io_out_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_out_bits_cmd_inst_funct = _GEN ? _q_io_deq_bits_0_cmd_inst_funct : 7'h5;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :47:36, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_out_bits_cmd_rs1 = _q_io_deq_pop_T_1 ? _q_io_deq_bits_0_cmd_rs1 : _state_T_1 ? _q_io_deq_bits_1_cmd_rs1 : state == 2'h2 ? {_q_io_deq_bits_0_cmd_rs1[63:32], 32'hFFFFFFFF} : _q_io_deq_bits_0_cmd_rs1;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :25:22, :38:{44,57}, :51:{36,52}, :62:20, :63:12, :64:12, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_out_bits_cmd_rs2 = _q_io_deq_pop_T_1 ? {_q_io_deq_bits_0_cmd_rs2[63:32], 32'hFFFFFFFF} : _state_T_1 ? _q_io_deq_bits_1_cmd_rs2 : _q_io_deq_bits_0_cmd_rs2;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :38:{44,57}, :41:{35,51}, :62:20, :63:12, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_out_bits_rob_id_valid = ~(_q_io_deq_pop_T_1 | _state_T_1);	// @[generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, :38:{44,57}, :62:20, :63:12, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_out_bits_rob_id_bits = _GEN ? _q_io_deq_bits_0_rob_id_bits : _q_io_deq_bits_1_rob_id_bits;	// @[generators/gemmini/src/main/scala/gemmini/MultiHeadedQueue.scala:53:19, generators/gemmini/src/main/scala/gemmini/TransposePreloadUnroller.scala:9:7, src/main/scala/chisel3/util/Mux.scala:126:16]
endmodule

