/* Generated by Yosys 0.63+161 (git sha1 5fd39ff3e, clang++ 18.1.8 -fPIC -O3) */

(* keep =  1  *)
(* top =  1  *)
(* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2348.1-2588.10" *)
module GenVMECmd(clock, reset, io_start, io_isBusy, io_inst, io_baddr, io_vmeCmd_ready, io_vmeCmd_valid, io_vmeCmd_bits_addr, io_vmeCmd_bits_len, io_vmeCmd_bits_tag, io_readLen, io_done);
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2349.18-2349.23" *)
  input clock;
  wire clock;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2350.18-2350.23" *)
  input reset;
  wire reset;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2351.18-2351.26" *)
  input io_start;
  wire io_start;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2352.18-2352.27" *)
  input io_isBusy;
  wire io_isBusy;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2353.18-2353.25" *)
  input [127:0] io_inst;
  wire [127:0] io_inst;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2354.18-2354.26" *)
  input [31:0] io_baddr;
  wire [31:0] io_baddr;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2355.18-2355.33" *)
  input io_vmeCmd_ready;
  wire io_vmeCmd_ready;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2356.18-2356.33" *)
  output io_vmeCmd_valid;
  wire io_vmeCmd_valid;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2357.18-2357.37" *)
  output [31:0] io_vmeCmd_bits_addr;
  wire [31:0] io_vmeCmd_bits_addr;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2358.18-2358.36" *)
  output [3:0] io_vmeCmd_bits_len;
  wire [3:0] io_vmeCmd_bits_len;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2359.18-2359.36" *)
  output [20:0] io_vmeCmd_bits_tag;
  wire [20:0] io_vmeCmd_bits_tag;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2360.18-2360.28" *)
  output [4:0] io_readLen;
  wire [4:0] io_readLen;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2361.18-2361.25" *)
  output io_done;
  wire io_done;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire [16:0] _000_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire _001_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire [19:0] _002_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire _003_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire [11:0] _004_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  wire [15:0] _005_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.18-2408.59" *)
  wire _006_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.18-2410.66" *)
  wire _007_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2432.25-2432.71" *)
  wire _008_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.7-2581.58" *)
  wire _009_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.18-2408.38" *)
  wire _010_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.18-2410.45" *)
  wire _011_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.48-2410.66" *)
  wire _012_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2434.29-2434.50" *)
  wire _013_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2424.35-2424.59" *)
  wire _014_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.27-2581.57" *)
  wire _015_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.33-2585.73" *)
  wire _016_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2400.24-2400.48" *)
  wire _017_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2401.24-2401.47" *)
  wire _018_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2432.38-2432.61" *)
  wire _019_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.41-2408.59" *)
  wire _020_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.14-2581.24" *)
  wire _021_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.14-2585.30" *)
  wire _022_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2412.18-2412.35" *)
  wire _023_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2432.38-2432.70" *)
  wire _024_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.14-2581.57" *)
  wire _025_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.14-2585.73" *)
  wire _026_;
  wire [11:0] _027_;
  wire [11:0] _028_;
  wire [19:0] _029_;
  wire [15:0] _030_;
  wire [16:0] _031_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2387.15-2387.21" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _GEN_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2402.15-2402.22" *)
  wire [16:0] _GEN_10;
  wire [10:0] _GEN_11;
  wire [10:0] _GEN_14;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2441.15-2441.22" *)
  wire [31:0] _GEN_16;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2442.15-2442.22" *)
  wire [31:0] _GEN_17;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2443.15-2443.22" *)
  wire [31:0] _GEN_19;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.9-2410.15" *)
  wire _GEN_2;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2444.15-2444.22" *)
  wire [31:0] _GEN_20;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2445.9-2445.16" *)
  wire _GEN_21;
  wire [31:0] _GEN_22;
  wire [31:0] _GEN_23;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2450.15-2450.22" *)
  wire [11:0] _GEN_26;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2385.15-2385.22" *)
  wire [35:0] _GEN_31;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2399.15-2399.22" *)
  wire [16:0] _GEN_32;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2404.15-2404.22" *)
  wire [16:0] _GEN_33;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2414.15-2414.22" *)
  wire [15:0] _GEN_35;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2416.15-2416.22" *)
  wire [15:0] _GEN_36;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2419.15-2419.22" *)
  wire [19:0] _GEN_37;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2420.15-2420.22" *)
  wire [15:0] _GEN_38;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2422.15-2422.22" *)
  wire [19:0] _GEN_39;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2411.9-2411.15" *)
  wire _GEN_4;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2429.15-2429.22" *)
  wire [15:0] _GEN_42;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2436.15-2436.22" *)
  wire [31:0] _GEN_43;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2439.15-2439.22" *)
  wire [31:0] _GEN_44;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2452.15-2452.22" *)
  wire [11:0] _GEN_45;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2412.9-2412.15" *)
  wire _GEN_6;
  wire [4:0] _GEN_8;
  wire [4:0] _GEN_9;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2406.15-2406.20" *)
  wire [15:0] _T_11;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2407.9-2407.14" *)
  wire _T_14;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2405.15-2405.19" *)
  wire [16:0] _T_8;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2431.15-2431.33" *)
  wire [19:0] _currentRowIdx_T_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2388.14-2388.35" *)
  wire [7:0] _firstMaxTransfer_T_2;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2455.14-2455.37" *)
  (* unused_bits = "4" *)
  wire [4:0] _io_vmeCmd_bits_len_T_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2435.15-2435.24" *)
  wire [19:0] _memRow_T;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2453.15-2453.41" *)
  wire [11:0] _rdCmdDestBlockIdxNext_T_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2454.15-2454.41" *)
  wire [11:0] _rdCmdDestBlockIdxNext_T_3;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2449.15-2449.35" *)
  wire [11:0] _rdCmdDestBlockIdx_T;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2438.14-2438.29" *)
  wire [7:0] _rdCmdExtAddr_T;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2440.15-2440.32" *)
  wire [31:0] _rdCmdExtAddr_T_2;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2421.15-2421.38" *)
  wire [15:0] _rdCmdStartIdxValid_T_2;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2423.9-2423.32" *)
  wire _rdCmdStartIdxValid_T_3;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2424.9-2424.32" *)
  wire _rdCmdStartIdxValid_T_4;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2425.9-2425.32" *)
  wire _rdCmdStartIdxValid_T_5;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2426.9-2426.32" *)
  wire _rdCmdStartIdxValid_T_6;
  wire [10:0] _rdCmdStartIdx_T_1;
  wire [10:0] _rdCmdStartIdx_T_3;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2397.15-2397.29" *)
  wire [15:0] _srcRowIdx_T_1;
  wire [10:0] _totalWidth_T_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2383.15-2383.32" *)
  (* unused_bits = "32 33 34 35" *)
  wire [35:0] _xfer_init_addr_T;
  wire [31:0] _xfer_init_addr_T_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2393.14-2393.26" *)
  reg [16:0] blocksReadNb;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2392.15-2392.29" *)
  wire [16:0] blocksReadSize;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2398.15-2398.29" *)
  wire [16:0] blocksRemained;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2391.8-2391.20" *)
  reg commandsDone;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2418.14-2418.27" *)
  reg [19:0] currentRowIdx;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2375.15-2375.30" *)
  (* unused_bits = "28 29 30 31" *)
  wire [31:0] dec_dram_offset;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2374.15-2374.30" *)
  (* unused_bits = "11 12 13 14 15" *)
  wire [15:0] dec_sram_offset;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2380.14-2380.24" *)
  wire [3:0] dec_xpad_0;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2381.14-2381.24" *)
  wire [3:0] dec_xpad_1;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2377.15-2377.24" *)
  wire [15:0] dec_xsize;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2378.15-2378.26" *)
  wire [15:0] dec_xstride;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2379.14-2379.24" *)
  wire [3:0] dec_ypad_0;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2376.15-2376.24" *)
  wire [15:0] dec_ysize;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2389.14-2389.30" *)
  wire [4:0] firstMaxTransfer;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2437.15-2437.21" *)
  wire [31:0] memRow;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2395.8-2395.18" *)
  reg newReadRow;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2409.15-2409.24" *)
  wire [16:0] nextBlRNb;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2451.15-2451.32" *)
  wire [11:0] rdCmdDestBlockIdx;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2448.14-2448.35" *)
  reg [11:0] rdCmdDestBlockIdxNext;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2382.14-2382.26" *)
  reg [31:0] rdCmdExtAddr;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2394.14-2394.34" *)
  reg [31:0] rdCmdExtAddrRowBegin;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2390.14-2390.27" *)
  reg [10:0] rdCmdStartIdx;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2427.9-2427.27" *)
  wire rdCmdStartIdxValid;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2403.14-2403.21" *)
  wire [4:0] readLen;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2396.14-2396.23" *)
  reg [15:0] srcRowIdx;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2434.9-2434.26" *)
  wire startIssueCmdRead;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.9-2408.15" *)
  wire stride;
  wire [10:0] totalWidth;
  wire [31:0] xfer_init_addr;
  assign _srcRowIdx_T_1 = srcRowIdx + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2397.32-2397.49" *) 1'h1;
  assign nextBlRNb = blocksReadNb + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2409.27-2409.49" *) io_readLen;
  assign _totalWidth_T_1 = io_inst[90:80] + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2415.33-2415.52" *) io_inst[123:120];
  assign totalWidth = _totalWidth_T_1 + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2417.28-2417.53" *) io_inst[127:124];
  assign _rdCmdStartIdxValid_T_2 = io_inst[79:64] + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2421.41-2421.60" *) io_inst[115:112];
  assign _rdCmdStartIdx_T_1 = io_inst[20:10] + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2428.36-2428.61" *) io_inst[123:120];
  assign _rdCmdStartIdx_T_3 = rdCmdStartIdx + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2430.36-2430.56" *) totalWidth;
  assign _currentRowIdx_T_1 = currentRowIdx + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2431.36-2431.57" *) 1'h1;
  assign memRow = rdCmdExtAddrRowBegin + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2437.24-2437.54" *) { io_inst[111:96], 4'h0 };
  assign _rdCmdExtAddr_T_2 = rdCmdExtAddr + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2440.35-2440.57" *) { io_readLen, 3'h0 };
  assign _rdCmdDestBlockIdxNext_T_1 = rdCmdDestBlockIdx + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2453.44-2453.71" *) io_readLen;
  assign _rdCmdDestBlockIdxNext_T_3 = rdCmdDestBlockIdxNext + (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2454.44-2454.75" *) io_readLen;
  assign _T_14 = io_vmeCmd_ready & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2407.17-2407.50" *) io_vmeCmd_valid;
  assign _006_ = _010_ & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.18-2408.59" *) _020_;
  assign stride = _006_ & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.18-2408.67" *) _T_14;
  assign _007_ = _011_ & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.18-2410.66" *) _012_;
  assign _rdCmdStartIdxValid_T_4 = _014_ & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2424.35-2424.85" *) _rdCmdStartIdxValid_T_3;
  assign _rdCmdStartIdxValid_T_5 = _rdCmdStartIdxValid_T_4 & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2425.35-2425.70" *) io_isBusy;
  assign startIssueCmdRead = _013_ & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2434.29-2434.71" *) io_vmeCmd_valid;
  assign io_vmeCmd_valid = _rdCmdStartIdxValid_T_5 & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2456.28-2456.77" *) _rdCmdStartIdxValid_T_6;
  assign _008_ = io_isBusy & (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2480.18-2480.64" *) _024_;
  assign _010_ = blocksReadNb == (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.18-2408.38" *) _T_8;
  assign _011_ = nextBlRNb == (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.18-2410.45" *) { io_inst[95:80], 1'h0 };
  assign _012_ = srcRowIdx == (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.48-2410.66" *) _T_11;
  assign _013_ = ! (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2434.29-2434.50" *) blocksReadNb;
  assign _014_ = currentRowIdx >= (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2424.35-2424.59" *) io_inst[115:112];
  assign _015_ = { io_inst[95:80], 1'h0 } >= (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.27-2581.57" *) blocksReadNb;
  assign _016_ = { io_readLen, 3'h0 } <= (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.33-2585.73" *) _firstMaxTransfer_T_2;
  assign _017_ = blocksRemained < (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2400.24-2400.48" *) _firstMaxTransfer_T_2[7:3];
  assign _018_ = blocksRemained < (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2401.24-2401.47" *) 5'h10;
  assign _rdCmdStartIdxValid_T_3 = currentRowIdx < (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2423.35-2423.58" *) _rdCmdStartIdxValid_T_2;
  assign _019_ = currentRowIdx < (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2480.31-2480.54" *) io_inst[115:112];
  assign _GEN_1 = rdCmdExtAddr % (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2387.24-2387.45" *) 8'h80;
  assign _020_ = srcRowIdx != (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2408.41-2408.59" *) _T_11;
  assign _rdCmdStartIdxValid_T_6 = ~ (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2426.35-2426.48" *) commandsDone;
  assign _021_ = ~ (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.14-2581.24" *) io_isBusy;
  assign _022_ = ~ (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.14-2585.30" *) io_vmeCmd_valid;
  assign xfer_init_addr = io_baddr | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2386.32-2386.61" *) { io_inst[53:26], 4'h0 };
  assign _GEN_2 = _007_ | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2410.18-2410.81" *) commandsDone;
  assign _001_ = reset | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2465.21-2465.35" *) _GEN_6;
  assign _023_ = io_start | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2466.9-2466.26" *) stride;
  assign _003_ = io_start | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2472.19-2472.37" *) _GEN_21;
  assign _024_ = _019_ | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2480.31-2480.63" *) stride;
  assign _025_ = _021_ | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2581.14-2581.57" *) _015_;
  assign _026_ = _022_ | (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2585.14-2585.73" *) _016_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    rdCmdExtAddr <= _GEN_22;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    rdCmdStartIdx <= _GEN_14;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    commandsDone <= _001_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    blocksReadNb <= _000_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    rdCmdExtAddrRowBegin <= _GEN_23;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    newReadRow <= _003_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    srcRowIdx <= _005_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    currentRowIdx <= _002_;
  (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2462.3-2516.6" *)
  always @(posedge clock)
    rdCmdDestBlockIdxNext <= _004_;
  assign _009_ = reset ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2580.9-2580.15|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2580.5-2582.8" *) 1'h0 : 1'h1;
  assign _027_ = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2486.20-2486.25|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2486.16-2488.10" *) _rdCmdDestBlockIdxNext_T_3 : rdCmdDestBlockIdxNext;
  assign _028_ = startIssueCmdRead ? (* full_case = 32'h00000001 *) (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2484.11-2484.28|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2484.7-2488.10" *) _rdCmdDestBlockIdxNext_T_1 : _027_;
  assign _004_ = io_vmeCmd_valid ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2483.9-2483.27|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2483.5-2489.8" *) _028_ : rdCmdDestBlockIdxNext;
  assign _029_ = _008_ ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2480.18-2480.64|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2480.14-2482.8" *) _currentRowIdx_T_1 : currentRowIdx;
  assign _002_ = io_start ? (* full_case = 32'h00000001 *) (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2478.9-2478.17|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2478.5-2482.8" *) 20'h00000 : _029_;
  assign _030_ = stride ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2475.18-2475.24|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2475.14-2477.8" *) _srcRowIdx_T_1 : srcRowIdx;
  assign _005_ = io_start ? (* full_case = 32'h00000001 *) (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2473.9-2473.17|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2473.5-2477.8" *) 16'h0000 : _030_;
  assign _031_ = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2468.18-2468.23|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2468.14-2470.8" *) nextBlRNb : blocksReadNb;
  assign _000_ = _023_ ? (* full_case = 32'h00000001 *) (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2466.9-2466.26|autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2466.5-2470.8" *) 17'h00000 : _031_;
  assign _firstMaxTransfer_T_2 = 8'h80 - (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2388.38-2388.57" *) _GEN_1[7:0];
  assign blocksRemained = { io_inst[95:80], 1'h0 } - (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2398.32-2398.61" *) blocksReadNb;
  assign _T_8 = { io_inst[95:80], 1'h0 } - (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2405.22-2405.46" *) io_readLen;
  assign _T_11 = io_inst[79:64] - (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2406.23-2406.40" *) 1'h1;
  assign io_vmeCmd_bits_len = io_readLen[3:0] - (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2455.40-2455.54" *) 1'h1;
  assign _GEN_8 = _017_ ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2400.24-2400.95" *) blocksRemained[4:0] : _firstMaxTransfer_T_2[7:3];
  assign _GEN_9 = _018_ ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2401.24-2401.73" *) blocksRemained[4:0] : 5'h10;
  assign io_readLen = newReadRow ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2402.25-2402.53" *) _GEN_8 : _GEN_9;
  assign _GEN_4 = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2411.18-2411.47" *) _GEN_2 : commandsDone;
  assign _GEN_6 = _023_ ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2412.18-2412.51" *) 1'h0 : _GEN_4;
  assign _GEN_11 = _008_ ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2432.25-2432.118" *) _rdCmdStartIdx_T_3 : rdCmdStartIdx;
  assign _GEN_14 = io_start ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2433.25-2433.64" *) _rdCmdStartIdx_T_1 : _GEN_11;
  assign _GEN_16 = stride ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2441.25-2441.60" *) memRow : _rdCmdExtAddr_T_2;
  assign _GEN_17 = stride ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2442.25-2442.63" *) memRow : rdCmdExtAddrRowBegin;
  assign _GEN_19 = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2443.25-2443.55" *) _GEN_16 : rdCmdExtAddr;
  assign _GEN_20 = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2444.25-2444.63" *) _GEN_17 : rdCmdExtAddrRowBegin;
  assign _GEN_21 = _T_14 ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2445.19-2445.46" *) stride : newReadRow;
  assign _GEN_22 = io_start ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2446.25-2446.70" *) xfer_init_addr : _GEN_19;
  assign _GEN_23 = io_start ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2447.25-2447.70" *) xfer_init_addr : _GEN_20;
  assign _GEN_26 = startIssueCmdRead ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2450.25-2450.89" *) { rdCmdStartIdx, 1'h0 } : rdCmdDestBlockIdxNext;
  assign rdCmdDestBlockIdx = io_vmeCmd_valid ? (* src = "autoGenILA/func_test/vta_load_cmd/RTL//VTA.DefaultDe10Config.sv:2451.35-2451.87" *) _GEN_26 : rdCmdDestBlockIdxNext;
  assign _GEN_10 = { 12'hxxx, io_readLen };
  assign _GEN_31 = { 4'h0, io_baddr };
  assign _GEN_32 = { 12'h000, _firstMaxTransfer_T_2[7:3] };
  assign _GEN_33 = { 12'h000, io_readLen };
  assign _GEN_35 = { 12'h000, io_inst[123:120] };
  assign _GEN_36 = { 12'h000, io_inst[127:124] };
  assign _GEN_37 = { 16'h0000, io_inst[115:112] };
  assign _GEN_38 = { 12'h000, io_inst[115:112] };
  assign _GEN_39 = { 4'h0, _rdCmdStartIdxValid_T_2 };
  assign _GEN_42 = { 5'h00, rdCmdStartIdx };
  assign _GEN_43 = { 12'h000, io_inst[111:96], 4'h0 };
  assign _GEN_44 = { 24'h000000, io_readLen, 3'h0 };
  assign _GEN_45 = { 7'h00, io_readLen };
  assign _io_vmeCmd_bits_len_T_1[3:0] = io_vmeCmd_bits_len;
  assign _memRow_T = { io_inst[111:96], 4'h0 };
  assign _rdCmdDestBlockIdx_T = { rdCmdStartIdx, 1'h0 };
  assign _rdCmdExtAddr_T = { io_readLen, 3'h0 };
  assign _xfer_init_addr_T = { io_inst[57:26], 4'h0 };
  assign _xfer_init_addr_T_1 = { io_inst[53:26], 4'h0 };
  assign blocksReadSize = { io_inst[95:80], 1'h0 };
  assign dec_dram_offset = io_inst[57:26];
  assign dec_sram_offset = io_inst[25:10];
  assign dec_xpad_0 = io_inst[123:120];
  assign dec_xpad_1 = io_inst[127:124];
  assign dec_xsize = io_inst[95:80];
  assign dec_xstride = io_inst[111:96];
  assign dec_ypad_0 = io_inst[115:112];
  assign dec_ysize = io_inst[79:64];
  assign firstMaxTransfer = _firstMaxTransfer_T_2[7:3];
  assign io_done = commandsDone;
  assign io_vmeCmd_bits_addr = rdCmdExtAddr;
  assign io_vmeCmd_bits_tag = { 9'h000, rdCmdDestBlockIdx };
  assign rdCmdStartIdxValid = io_vmeCmd_valid;
  assign readLen = io_readLen;
endmodule
